# Generated by Django 3.0.8 on 2020-09-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='SOME STRING', max_length=1000, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/300.jpg', verbose_name='profile photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='Brisbane', max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='0481041798', max_length=13, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=80, verbose_name='password'),
        ),
    ]
